name: Automated co2-ppm-daily update

on:
  schedule:
    # Run weekly
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Run co2-ppm-daily-flow
      run: |
        python scripts/co2-ppm-daily-flow.py

    - name: Configure Git
      run: |
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git config --global user.name "${{ env.CI_COMMIT_NAME }}"
      env:
        CI_COMMIT_NAME: "Automated commit"
        CI_COMMIT_EMAIL: "actions@users.noreply.github.com"

    - name: Commit and Push changes
      run: |
        git diff --quiet && echo "No changes to commit" || (
          git add data/ datapackage.json &&
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" &&
          git push origin main
        )
      env:
        CI_COMMIT_MESSAGE: "Automated commit"